manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll   # ←ここが重要
    - name: zmk-pmw3610-driver
      remote: inorichi
      path: zmk-pmw3610-driver
  self:
    path: config
